export const SEARCH_FOCUS = 'SEARCH_FOCUS'
export const SEARCH_BLUR= 'SEARCH_BLUR'
export const CHANGE_LIST = 'CHANGE_LIST'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const MOUSE_ENTER = 'MOUSE_ENTER'
export const MOUTER_LEAVE = 'MOUSE_LEAVE'